### PR TITLE
Fix installer to use ID_NET_NAME_PATH

### PR DESCRIPTION
**Pull request by chmaikos**
* Readme cleanup
* Changed the network_setup function to utilize the ID_NET_NAME_PATH variable.

Source is described here: https://www.freedesktop.org/software/systemd/man/latest/systemd.net-naming-scheme.html

Most servers require this naming to be set in /etc/network/interfaces in order for networking to work after rebooting

### CODE REVIEW

**Comment by WMP** [comment]
And does ID_NET_NAME_PATH work on your hetzner servers? It didn't work for me, but it did in the early stages of the script.

**Comment by chmaikos** [comment]
I have tested in AX41 and a couple auction servers I have for labs. So far all hetzner servers I had used this naming scheme for networking.

If unsure I can add a check to see which variable is not empty and use that, although this might introduce other errors down the line if both are populated somehow (unlikely)

**Comment by WMP** [comment]
Maybe you can add an argument in the script to select this? It can default with the value you suggest.  I unfortunately no longer have a way to test the script, I no longer have a server that I can reinstall.

In addition, in the days I plan to add a simple scp that will upload the indicated file (configuration of another network) to /etc/network/interfaces.d.

Thank you for your work and for your interest in my script, thanks to seeing your commits I decided to spend a few more hours on it.

**Comment by chmaikos** [comment]
* Added sanity check to user for network config
* Added function to print possible IFACE_NAMES and ask the user which one to use

Tested on AX41, AX52 and EX44

**Comment by WMP** [comment]
I don't like that there is a prompt that waits for the user to type something, this is weak for automation. The script is supposed to work right away and be easy to run with the same parameters. As one uses arguments in bash I can write down in notepad that I install hetzner servers using these arguments.

Maybe we can make the interfaces display in --help? And using the --public-nic IFACE_NAME parameter to set the interface name?



Why are you replacing hetzner's DNS resolvers with those from cloudflare?

DNS in general needs to be rewritten.... Such a configuration works well if you don't have an internal DNS server in the vSwitch network. Unfortunately, I don't know how to describe in proxmox that DNS on the address from vSwitch's vlan handles only my internal domain, as is done using resolvectl .

**Comment by chmaikos** [comment]
* Added --verbose switch to enable QEMU and Network command logging
* Added --iface-name switch to directly supply the path of the WAN interface. ID_NET_NAME_PATH is used as default.
* Added --list-ifaces switch to print the paths of all interfaces and exit
* Reverted DNS to Hetzner Servers

With this changes the script is almost fully automated, expecting only the ssh password as input

**Comment by WMP** [comment]
Thank you for your work ;) I corrected the DNS and changed the verbose a bit, if you have a server please check if it works.

**Pull request merged**
